### ISSUE TITLE
Assertion failure trying to compile a macro

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [shikantaza/pLisp#30] opened 2016-04-17 09:43 UTC
pLisp says: `plisp: src/full_monty_compiler.c:2859: extract_variable_string: Assertion `0' failed.`

...when trying to compile the following form:

```
(defmacro let-special (defs &rest body)
  (let ((gensyms (mapcar (lambda (ignored)
                           (gensym)) defs)))
    `(let ,(mapcar
            (lambda (sym def)
              `(,sym ,(car def)))
            gensyms defs)
       (unwind-protect
            (progn
               ,@(mapcar (lambda (def)
                           (cons 'set def))
                         defs)
               ,@body)
         (progn
           ,@(mapcar (lambda (def sym)
                       `(set ,(car def) ,sym))
                     defs gensyms))))))

```

**Comment by shikantaza** [comment] 2016-04-17 09:55
I think the issue is with the presence of the nested backquote, this is not handled yet -- to be honest I haven't dwelt that deeply yet into what level of support wrt macros (as compared to, say, Common Lisp) should be provided. At the least, the assert should be converted into an exception, will do this.

**Comment by heegaiximephoomeeghahyaiseekh** [comment] 2016-04-17 15:33
It looks like you try to handle `BACKQUOTE` entirely in the compiler. That's doing it the hard way. `BACKQUOTE` is usually implemented as an ordinary macro. That way you can write it in Lisp instead of C.

Here's a complete implementation of the macro:

[qq.zip](https://github.com/shikantaza/pLisp/files/222704/qq.zip)

All that's left to do is make sure that the compiler does no special processing on the `backquote`, `comma`, and `comma-at` symbols.

**Comment by shikantaza** [comment] 2016-04-17 16:36
Thanks, really apreciate your feedback and directions. Implementing bsckquote entirely as a macro is very appealing (not to mention less gnarly). Will work on this.

**Comment by shikantaza** [comment] 2016-05-27 05:35
The issue was with incorrect handling of `&rest` parameters during compilation. Have fixed this and have implemented a new `mapcar` as well. The `let-special` macro above works now. Closing the issue, thanks.

**Closed by shikantaza** 2016-05-27 05:35 UTC
